"""
Persistence utilities for SparseTensor.

* ``safetensors`` format for efficient, safe serialisation.
* Matrix Market (``.mtx``) for interop with SciPy and other tools.

::

    from torch_sla import SparseTensor
    from torch_sla.io import save_sparse, load_sparse

    A = SparseTensor(val, row, col, shape)
    save_sparse(A, "matrix.safetensors")
    A = load_sparse("matrix.safetensors")
"""

import os
import json
import torch
from typing import Dict, Optional, Tuple, Union, TYPE_CHECKING
from pathlib import Path

if TYPE_CHECKING:
    from .sparse_tensor import SparseTensor

try:
    from safetensors.torch import save_file, load_file
    SAFETENSORS_AVAILABLE = True
except ImportError:
    SAFETENSORS_AVAILABLE = False


def _ensure_safetensors():
    """Ensure safetensors is available."""
    if not SAFETENSORS_AVAILABLE:
        raise ImportError(
            "safetensors is required for persistence. "
            "Install with: pip install safetensors"
        )


# =============================================================================
# Matrix Market (.mtx) Format
# =============================================================================

def save_mtx(
    tensor: "SparseTensor",
    path: Union[str, Path],
    comment: str = "",
    field: str = "real",
    symmetry: str = "general",
) -> None:
    """
    Save a SparseTensor to Matrix Market (.mtx) format.
    
    Parameters
    ----------
    tensor : SparseTensor
        The sparse tensor to save.
    path : str or Path
        Output file path (should end with .mtx).
    comment : str, optional
        Comment to include in the header.
    field : str, optional
        Field type: 'real', 'complex', 'integer', or 'pattern'.
        Default: 'real'.
    symmetry : str, optional
        Symmetry type: 'general', 'symmetric', 'skew-symmetric', or 'hermitian'.
        Default: 'general'.
    
    Example
    -------
    >>> A = SparseTensor(val, row, col, (100, 100))
    >>> save_mtx(A, "matrix.mtx")
    >>> save_mtx(A, "matrix.mtx", symmetry="symmetric")
    """
    from .sparse_tensor import SparseTensor
    
    if not isinstance(tensor, SparseTensor):
        raise TypeError(f"Expected SparseTensor, got {type(tensor)}")
    
    if tensor.is_batched:
        raise ValueError("Cannot save batched SparseTensor to Matrix Market format")
    
    path = Path(path)
    M, N = tensor.sparse_shape
    nnz = tensor.nnz
    
    # Get data on CPU
    row = tensor.row_indices.cpu().numpy()
    col = tensor.col_indices.cpu().numpy()
    val = tensor.values.cpu().numpy()
    
    # Determine field type from dtype
    if tensor.dtype in (torch.complex64, torch.complex128):
        field = "complex"
    elif tensor.dtype in (torch.int32, torch.int64):
        field = "integer"
    
    with open(path, 'w') as f:
        # Write header
        f.write(f"%%MatrixMarket matrix coordinate {field} {symmetry}\n")
        if comment:
            for line in comment.split('\n'):
                f.write(f"% {line}\n")
        f.write(f"% Generated by torch-sla\n")
        
        # Write dimensions
        f.write(f"{M} {N} {nnz}\n")
        
        # Write entries (1-indexed)
        if field == "pattern":
            for i in range(nnz):
                f.write(f"{row[i] + 1} {col[i] + 1}\n")
        elif field == "complex":
            for i in range(nnz):
                v = val[i]
                f.write(f"{row[i] + 1} {col[i] + 1} {v.real} {v.imag}\n")
        else:
            for i in range(nnz):
                f.write(f"{row[i] + 1} {col[i] + 1} {val[i]}\n")


def load_mtx(
    path: Union[str, Path],
    dtype: Optional[torch.dtype] = None,
    device: Union[str, torch.device] = "cpu",
) -> "SparseTensor":
    """
    Load a SparseTensor from Matrix Market (.mtx) format.
    
    Parameters
    ----------
    path : str or Path
        Input file path.
    dtype : torch.dtype, optional
        Data type for values. If None, inferred from file.
    device : str or torch.device
        Device to load tensors to.
    
    Returns
    -------
    SparseTensor
        The loaded sparse tensor.
    
    Example
    -------
    >>> A = load_mtx("matrix.mtx")
    >>> A = load_mtx("matrix.mtx", dtype=torch.float32, device="cuda")
    """
    from .sparse_tensor import SparseTensor
    import numpy as np
    
    path = Path(path)
    
    with open(path, 'r') as f:
        # Parse header
        header = f.readline().strip()
        if not header.startswith("%%MatrixMarket"):
            raise ValueError(f"Invalid Matrix Market header: {header}")
        
        parts = header.split()
        if len(parts) < 4:
            raise ValueError(f"Invalid Matrix Market header: {header}")
        
        obj_type = parts[1].lower()  # matrix
        format_type = parts[2].lower()  # coordinate
        field_type = parts[3].lower() if len(parts) > 3 else "real"
        symmetry = parts[4].lower() if len(parts) > 4 else "general"
        
        if obj_type != "matrix":
            raise ValueError(f"Only 'matrix' object type supported, got: {obj_type}")
        if format_type != "coordinate":
            raise ValueError(f"Only 'coordinate' format supported, got: {format_type}")
        
        # Skip comments
        line = f.readline()
        while line.startswith('%'):
            line = f.readline()
        
        # Parse dimensions
        dims = line.strip().split()
        M, N, nnz = int(dims[0]), int(dims[1]), int(dims[2])
        
        # Parse entries
        rows = []
        cols = []
        vals = []
        
        for line in f:
            parts = line.strip().split()
            if not parts:
                continue
            
            r = int(parts[0]) - 1  # Convert to 0-indexed
            c = int(parts[1]) - 1
            
            if field_type == "pattern":
                v = 1.0
            elif field_type == "complex":
                v = complex(float(parts[2]), float(parts[3]))
            elif field_type == "integer":
                v = int(parts[2])
            else:
                v = float(parts[2])
            
            rows.append(r)
            cols.append(c)
            vals.append(v)
            
            # Handle symmetry
            if symmetry == "symmetric" and r != c:
                rows.append(c)
                cols.append(r)
                vals.append(v)
            elif symmetry == "skew-symmetric" and r != c:
                rows.append(c)
                cols.append(r)
                vals.append(-v)
            elif symmetry == "hermitian" and r != c:
                rows.append(c)
                cols.append(r)
                vals.append(v.conjugate() if isinstance(v, complex) else v)
    
    # Convert to tensors
    row_tensor = torch.tensor(rows, dtype=torch.long, device=device)
    col_tensor = torch.tensor(cols, dtype=torch.long, device=device)
    
    # Determine dtype
    if dtype is None:
        if field_type == "complex":
            dtype = torch.complex128
        elif field_type == "integer":
            dtype = torch.int64
        else:
            dtype = torch.float64
    
    val_tensor = torch.tensor(vals, dtype=dtype, device=device)
    
    return SparseTensor(val_tensor, row_tensor, col_tensor, (M, N))


def load_mtx_info(path: Union[str, Path]) -> Dict:
    """
    Read Matrix Market file header without loading data.
    
    Parameters
    ----------
    path : str or Path
        Input file path.
    
    Returns
    -------
    dict
        Dictionary with keys: 'shape', 'nnz', 'field', 'symmetry'.
    
    Example
    -------
    >>> info = load_mtx_info("matrix.mtx")
    >>> print(f"Shape: {info['shape']}, NNZ: {info['nnz']}")
    """
    path = Path(path)
    
    with open(path, 'r') as f:
        header = f.readline().strip()
        parts = header.split()
        
        field_type = parts[3].lower() if len(parts) > 3 else "real"
        symmetry = parts[4].lower() if len(parts) > 4 else "general"
        
        # Skip comments
        line = f.readline()
        while line.startswith('%'):
            line = f.readline()
        
        dims = line.strip().split()
        M, N, nnz = int(dims[0]), int(dims[1]), int(dims[2])
    
    return {
        'shape': (M, N),
        'nnz': nnz,
        'field': field_type,
        'symmetry': symmetry,
    }


# =============================================================================
# SparseTensor I/O
# =============================================================================

def save_sparse(
    tensor: "SparseTensor",
    path: Union[str, Path],
    metadata: Optional[Dict[str, str]] = None
) -> None:
    """
    Save a SparseTensor to safetensors format.
    
    Parameters
    ----------
    tensor : SparseTensor
        The sparse tensor to save.
    path : str or Path
        Output file path (should end with .safetensors).
    metadata : dict, optional
        Additional metadata to store in the file.
    
    Example
    -------
    >>> A = SparseTensor(val, row, col, (100, 100))
    >>> save_sparse(A, "matrix.safetensors")
    """
    _ensure_safetensors()
    from .sparse_tensor import SparseTensor
    
    if not isinstance(tensor, SparseTensor):
        raise TypeError(f"Expected SparseTensor, got {type(tensor)}")
    
    # Prepare tensors dict
    tensors = {
        "values": tensor.values.contiguous().cpu(),
        "row_indices": tensor.row_indices.contiguous().cpu(),
        "col_indices": tensor.col_indices.contiguous().cpu(),
        "shape": torch.tensor(tensor.sparse_shape, dtype=torch.int64),
    }
    
    # Prepare metadata
    meta = {
        "sparse_dim_0": str(tensor.sparse_dim[0]),
        "sparse_dim_1": str(tensor.sparse_dim[1]),
        "dtype": str(tensor.dtype),
        "format": "sparse_tensor",
        "version": "1.0",
    }
    if metadata:
        meta.update(metadata)
    
    save_file(tensors, str(path), metadata=meta)


def load_sparse(
    path: Union[str, Path],
    device: Union[str, torch.device] = "cpu"
) -> "SparseTensor":
    """
    Load a SparseTensor from safetensors format.
    
    Parameters
    ----------
    path : str or Path
        Input file path.
    device : str or torch.device
        Device to load tensors to.
    
    Returns
    -------
    SparseTensor
        The loaded sparse tensor.
    
    Example
    -------
    >>> A = load_sparse("matrix.safetensors", device="cuda")
    """
    _ensure_safetensors()
    from .sparse_tensor import SparseTensor
    
    tensors = load_file(str(path), device=str(device))
    
    values = tensors["values"]
    row_indices = tensors["row_indices"]
    col_indices = tensors["col_indices"]
    shape = tuple(tensors["shape"].tolist())
    
    return SparseTensor(values, row_indices, col_indices, shape)


# =============================================================================
# Distributed I/O - Save partitioned for multi-rank loading
# =============================================================================

def load_metadata(directory: Union[str, Path]) -> Dict:
    """
    Load metadata from a distributed sparse tensor directory.
    
    Parameters
    ----------
    directory : str or Path
        Directory containing partitioned data.
    
    Returns
    -------
    dict
        Metadata including shape, dtype, num_partitions, etc.
    
    Example
    -------
    >>> meta = load_metadata("matrix_dist")
    >>> print(f"Shape: {meta['shape']}, Partitions: {meta['num_partitions']}")
    """
    directory = Path(directory)
    with open(directory / "metadata.json", "r") as f:
        return json.load(f)
